version = 0.1
[default.deploy.parameters]
stack_name = "dynamodb-crud-app"
resolve_s3 = true
s3_prefix = "dynamodb-crud-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
