version = 0.1
[default.deploy.parameters]
stack_name = "simple-crud-aws-serverless"
resolve_s3 = true
s3_prefix = "simple-crud-aws-serverless"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
